"""Add fileName, contentType, workspaceId to source_files and rename snippet to content_text in vectors

Revision ID: f01dcb81fc6c
Revises: f5038814c03c
Create Date: 2025-06-04 09:57:27.378961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f01dcb81fc6c'
down_revision: Union[str, None] = 'f5038814c03c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add new columns as nullable first
    op.add_column('source_files', sa.Column('file_name', sa.String(length=255), nullable=True))
    op.add_column('source_files', sa.Column('content_type', sa.String(length=100), nullable=True))
    op.add_column('source_files', sa.Column('workspace_id', sa.String(length=255), nullable=True))
    op.add_column('source_files', sa.Column('file_size', sa.Integer(), nullable=True))
    
    # Update existing records with default values
    op.execute("""
        UPDATE source_files 
        SET 
            file_name = CASE 
                WHEN file_path LIKE '%/%' THEN split_part(file_path, '/', -1)
                ELSE file_path 
            END,
            content_type = 'application/octet-stream',
            workspace_id = 'default'
        WHERE file_name IS NULL OR content_type IS NULL OR workspace_id IS NULL
    """)
    
    # Make columns NOT NULL
    op.alter_column('source_files', 'file_name', nullable=False)
    op.alter_column('source_files', 'content_type', nullable=False)
    op.alter_column('source_files', 'workspace_id', nullable=False)
    
    # Handle vectors table - rename column
    op.add_column('vectors', sa.Column('content_text', sa.Text(), nullable=True))
    op.execute("UPDATE vectors SET content_text = snippet WHERE content_text IS NULL")
    op.alter_column('vectors', 'content_text', nullable=False)
    op.drop_column('vectors', 'snippet')
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vectors', sa.Column('snippet', sa.TEXT(), autoincrement=False, nullable=True))
    op.execute("UPDATE vectors SET snippet = content_text WHERE snippet IS NULL")
    op.alter_column('vectors', 'snippet', nullable=False)
    op.drop_column('vectors', 'content_text')
    op.drop_column('source_files', 'file_size')
    op.drop_column('source_files', 'workspace_id')
    op.drop_column('source_files', 'content_type')
    op.drop_column('source_files', 'file_name')
    # ### end Alembic commands ###
