"""Add workspace_id to data_items table

Revision ID: f5038814c03c
Revises: 5f0a4c72a78a
Create Date: 2025-06-03 14:04:10.320368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5038814c03c'
down_revision: Union[str, None] = '5f0a4c72a78a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_items', sa.Column('workspace_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'data_items', 'workspaces', ['workspace_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'data_items', type_='foreignkey')
    op.drop_column('data_items', 'workspace_id')
    # ### end Alembic commands ###
